---
abstract: 'an easier way to export functions'
author:
  - 'Ben Morrow <ben@morrow.me.uk>'
build_requires:
  Test::Exports: 1
  Test::More: 0.61
configure_requires:
  Module::Build: 0.36
generated_by: 'Module::Build version 0.3607'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Exporter-NoWork
provides:
  Exporter::NoWork:
    file: lib/Exporter/NoWork.pm
    version: 0.03
requires:
  Attribute::Handlers: 0.80
resources:
  bugtracker: https://rt.cpan.org/Public/Dist/Display.html?Name=Exporter-NoWork
  license: http://dev.perl.org/licenses/
  repository: http://github.com/mauzo/Exporter-NoWork
version: 0.03
